version: '3'

services:
  news-api:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./news-api:/news-api
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: postgres